#!/bin/sh

cd "`dirname "$0"`"

cd futures_market

if [ -e /usr/bin/python26 ]; then
    # on DLN's machine
    /usr/bin/python26 manage.py runtornado 127.0.0.1:8000
else
    python manage.py runtornado 0.0.0.0:9000
fi

