#!/bin/sh

cd "`dirname "$0"`"

cd futures_market

if [ -e /usr/bin/python26 ]; then
    # on DLN's machine
    /usr/bin/python26 manage.py syncdb
    /usr/bin/python26 manage.py createcachetable db_cache
else
    python manage.py syncdb
    python manage.py createcachetable db_cache
fi
